name: Generate VMF Sample

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-vmf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: python tools/make_vmf_sample.py
      - name: Commit VMF sample
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/samples/sample_vmf.bin
          git commit -m "Auto-generate VMF sample" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
