name: Generate VMF Sample

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-vmf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps (none required)
        run: python -m pip install --upgrade pip

      - name: Generate VMF sample
        run: python tools/make_vmf_sample.py

      # Only commit/push when this is NOT a pull_request run.
      - name: Commit and push to branch
        if: ${{ github.event_name != 'pull_request' }}
        shell: bash
        run: |
          set -e
          BRANCH="bot/gen-vmf-sample"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B "$BRANCH"
          git add data/samples/sample_vmf.bin
          git commit -m "Auto-generate VMF sample" || echo "No changes to commit"
          git push --force-with-lease origin "$BRANCH"

      # On PRs, simply confirm success and print the compare link (no push)
      - name: PR info
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Validation run complete for PR #${{ github.event.number }}."
          echo "This job is required and will show as 'generate-vmf' in checks."
