name: Generate VMF Sample

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-vmf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Keep credentials so git push works with the GITHUB_TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps (none required)
        run: python -m pip install --upgrade pip

      - name: Generate VMF sample
        run: python tools/make_vmf_sample.py

      - name: Commit and push to branch
        shell: bash
        run: |
          set -e
          BRANCH="bot/gen-vmf-sample"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create or update the branch
          git checkout -B "$BRANCH"

          git add data/samples/sample_vmf.bin
          git commit -m "Auto-generate VMF sample" || echo "No changes to commit"

          # Push branch to origin (create if missing, update if exists)
          git push --force-with-lease origin "$BRANCH"

          # Print a PR link you can click manually
          echo ""
          echo "Open a PR with this branch:"
          echo "  ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/pull/new/${BRANCH}"
          echo ""
          echo "If branch protection blocks direct pushes to main, merge this PR to apply the change."
