name: Generate VMF Sample

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-vmf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Keep credentials so git push works with the GITHUB_TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps (none required)
        run: python -m pip install --upgrade pip

      - name: Generate VMF sample
        run: python tools/make_vmf_sample.py

      - name: Commit and push VMF sample
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/samples/sample_vmf.bin
          git commit -m "Auto-generate VMF sample" || echo "No changes to commit"
          git push
